### ISSUE TITLE
Default names for images showing weird results

### ISSUE THREAD

**Issue by TNTzx** [naoei/VADB-Issue-Tracker#16]
apparently sending the image as `"avatar.png"` and `"banner.png"` wouldn't change anything, but i think internally it did change
the original image before the request remained as the one being shown on the site
but after sending requests, you can't change the image, even with the site's admin edit page

**Comment by naoei** [comment]
Can you include steps to reproduce? It's a bit hard to figure out exactly what you're saying here. From what I can understand, your browser is using the cached version of the images instead of the ones on the server. Can you hit <kbd>Ctrl</kbd> + <kbd>R</kbd> to see if this fixes the issue?

**Comment by TNTzx** [comment]
definitely not the cache, actually more weird stuff happens

1. in the vadb site, edit any artist
2. upload any image named `"avatar.png"` as the artist's avatar
3. press "edit"
4. attempt to edit that artist's avatar again

**Comment by naoei** [comment]
I can't seem to replicate the issue on 118. Can you share your console whenever you get the "undefined" alert?

**Comment by TNTzx** [comment]
hm, the bug seems to be gone now, i suppose it's a cache issue then
